a=int(input('Numarul de oua pe care il da prima gaine este'))
b=int(input('Numarul de oua pe care il da a doua gaine este'))
c=int(input('Numarul de oua pe care il da a treia gaine este'))
d=int(input('Numarul de oua pe care il da a patra gaine este'))
print('intr-o saptamana se obtin', 7*(a+b+c+d))